### ISSUE TITLE
new p2.Shape({ material: ... }) not documented

### ISSUE THREAD

**Issue by DelvarWorld** [schteppe/p2.js#215]
[According to the source code](http://schteppe.github.io/p2.js/docs/files/src_shapes_Shape.js.html#l121), you can pass in a material to the constructor of a shape.
```js
this.material = options.material || null;
```
However this isn't mentioned in [the shape documentation](http://schteppe.github.io/p2.js/docs/classes/Shape.html).

Also [the friction demo](http://schteppe.github.io/p2.js/demos/friction.html) doesn't take advantage of the `material` in the `Shape` constructor:

```js
var slipperyShape = new p2.Circle({ radius: 0.5 });
slipperyShape.material = new p2.Material();
```

Additionally, why did you choose to put the material on the shape instead of the body (like Cannon does it?)

**Comment by schteppe** [comment]
You're right, this should definitely be documented and brought more into the light. Thanks for the heads up.

If you look closer you see that Cannon.js has support for both per-body and per-shape materials. The reason why I added per-shape materials to Cannon is that I wanted to enable workflows like in Unity, where you specify friction and restitution per Collider Component. And also because Box2d has it.
I believe per-shape is the way to go, because per-body is more limiting.

**Comment by schteppe** [comment]
Turns out it was already documented. However, I made the demos use the constructor option. Much cleaner. Thanks.
