### ISSUE TITLE
Ignore collision between bodies/players

### ISSUE THREAD

**Issue by issy123** [schteppe/p2.js#316]
Hi,

I want the players to go through each other, thus ignore collision between players.
The players still can collide with everything else.
And I can still detect if a collision has occured between players.

Is this somehow possible?? 

With box2d you have collision filtering, but i don't think you can still detect collisions between same bodies.

**Comment by schteppe** [comment]
Hi. It’s indeed possible and it’s demonstrated in the character demo: https://github.com/schteppe/p2.js/blob/master/examples/canvas/character.html

The idea is to let the World generate contacts as it usually does, and then before contact solving you disable them. This will enable you to get events, but the contacts will not add contact force because you disable them.

**Comment by issy123** [comment]
Thank you so much sir!

I will read into this when I have time

**Comment by issy123** [comment]
hi @schteppe It works! But...
When the player comes in contact with the body it does some small weird movement. Is there some collision or damping or anything before the 'preSolve' event?

**Comment by issy123** [comment]
Wait... 

I forgot the frictionEquations! It works 100% Thanks!
